backends:
  deepeval:
    module: "rhesis.sdk.metrics.providers.deepeval"
    factory: "DeepEvalMetricFactory"
  ragas:
    module: "rhesis.sdk.metrics.providers.deepeval"
    factory: "RagasMetricFactory"
  rhesis:
    module: "rhesis.sdk.metrics.providers.native"
    factory: "RhesisMetricFactory"
  custom:
    module: "rhesis.sdk.metrics.providers.native"
    factory: "RhesisMetricFactory"
  garak:
    module: "rhesis.sdk.metrics.providers.garak"
    factory: "GarakMetricFactory"
