{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    tier: backend
    {{- include "rhesis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: backend
    tier: backend
{{- end }}

{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    tier: frontend
    {{- include "rhesis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: frontend
    tier: frontend
{{- end }}

{{- if .Values.worker.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: worker
    tier: worker
    {{- include "rhesis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: {{ .Values.worker.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: worker
    tier: worker
{{- end }}

{{- if .Values.chatbot.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot
  namespace: {{ .Release.Namespace }}
  labels:
    app: chatbot
    tier: chatbot
    {{- include "rhesis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.chatbot.service.type }}
  ports:
    - port: {{ .Values.chatbot.service.port }}
      targetPort: {{ .Values.chatbot.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: chatbot
    tier: chatbot
{{- end }}

{{- if .Values.docs.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: docs
  namespace: {{ .Release.Namespace }}
  labels:
    app: docs
    tier: docs
    {{- include "rhesis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.docs.service.type }}
  ports:
    - port: {{ .Values.docs.service.port }}
      targetPort: {{ .Values.docs.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: docs
    tier: docs
{{- end }}