name: "[Release] 3. Publish and deploy (prd)"
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  publish:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.RHEO_APP_ID }}
          private-key: ${{ secrets.RHEO_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
                 
        
      - name: Set up Git
        run: |
            git config user.name "rheo-app[bot]"
            git config user.email "237771051+rheo-app[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv for SDK
        uses: astral-sh/setup-uv@v6
        with:
            version: latest
          
      - name: Run publish script
        run: |
          python3 .github/release --publish

        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Close release PR and merge to main
        run: |
          gh pr merge --auto --merge
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

  backend-deploy:
    needs: publish
    uses: ./.github/workflows/backend.yml
    with:
      environment: prd
      reason: "Release deployment to prd"
    secrets: inherit

  frontend-deploy:
    needs: publish
    uses: ./.github/workflows/frontend.yml
    with:
      environment: prd
      reason: "Release deployment to prd"
    secrets: inherit

  worker-deploy:
    needs: publish
    uses: ./.github/workflows/worker.yml
    with:
      environment: prd
      reason: "Release deployment to prd"
    secrets: inherit      
