name: "[Test] SDK"

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'sdk/**'
  push:
    branches: [ main ]
    paths:
      - 'sdk/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for git diff

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: latest
        enable-cache: true

    # - name: Type check SDK
    #   run: |
    #     cd sdk
    #     uv run pyright
    #   continue-on-error: false

    - name: Test SDK (fast)
      run: |
        cd sdk
        make test
      continue-on-error: false

    - name: Test SDK (full)
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
      run: |
        cd sdk
        uv sync --extra all
        make test-integration
      continue-on-error: false
